name: '@nativescript/core -> npm'
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: auto
        description: What kind of version upgrade
        options: 
        - auto
        - patch
        - minor
        - major
        - none


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          name: Martin Guillon
          email: dev@akylas.fr
      
      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Enable CorePack
        run: |
          corepack enable 
          yarn config get globalFolder # the yarn command will ensure the correct yarn version is downloaded and installed

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get globalFolder)"

      - name: Install deps
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --silent
        env: 
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
  

      - name: bump release auto
        if: github.event.inputs.release_type == 'auto' 
        run: |
          npm run core:changelog --

      - name: publish
        if: github.event.inputs.release_type != 'auto' && github.event.inputs.release_type != 'none'
        run: |
          npm run core:changelog -- --release-as ${{ github.event.inputs.release_type }}

      - name: publish
        run: |
          npm run core:publish -- --no-verify-access --no-private --no-commit-hooks --force-publish --yes
          git push --tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
